version: '2.3'

services:
  johncena:
    # image: collaborating.tuhh.de:5005/cmx8665/master-thesis/darknet:latest
    build:
      context: ./
      dockerfile: test.Dockerfile
    environment:
      - "QT_X11_NO_MITSHM=1"
      - "DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./shared_vol:/shared_cena
    runtime: nvidia
    command: sleep infinity